// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyB2cqQF2vCC2L3hDEnU2WUuxTfI0txUrv0',
    appId: '1:238504003364:web:9a8fcc316173042d0955b1',
    messagingSenderId: '238504003364',
    projectId: 'cloud-images-5d0ee',
    authDomain: 'cloud-images-5d0ee.firebaseapp.com',
    storageBucket: 'cloud-images-5d0ee.appspot.com',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCd_yLv11a1pcM0Vz68S5A8CVlPvb4aRtc',
    appId: '1:238504003364:android:5deafa3c377770f30955b1',
    messagingSenderId: '238504003364',
    projectId: 'cloud-images-5d0ee',
    storageBucket: 'cloud-images-5d0ee.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyAKd9NTJx_qtqVWZ_8DMG4lJL5eRtb4cac',
    appId: '1:238504003364:ios:3828cb0f68fd37f30955b1',
    messagingSenderId: '238504003364',
    projectId: 'cloud-images-5d0ee',
    storageBucket: 'cloud-images-5d0ee.appspot.com',
    iosClientId:
        '238504003364-33akoc6n2ea4no2am108f41fu2j1tcb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoappBackend',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyAKd9NTJx_qtqVWZ_8DMG4lJL5eRtb4cac',
    appId: '1:238504003364:ios:3828cb0f68fd37f30955b1',
    messagingSenderId: '238504003364',
    projectId: 'cloud-images-5d0ee',
    storageBucket: 'cloud-images-5d0ee.appspot.com',
    iosClientId:
        '238504003364-33akoc6n2ea4no2am108f41fu2j1tcb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoappBackend',
  );
}
